In [ ]:
from transformers import ViTForImageClassification, ViTFeatureExtractor, Trainer, TrainingArguments
from PIL import Image
import torch
import pandas as pd
import os
from torch.utils.data import Dataset, random_split

In [ ]:
#google/vit-huge-patch14-224-in21k 0.9888
#google/vit-base-patch32-384 0.986

In [ ]:
model_name = "google/vit-base-patch32-384"
model = ViTForImageClassification.from_pretrained(model_name, num_labels=2,ignore_mismatched_sizes=True)
feature_extractor = ViTFeatureExtractor.from_pretrained(model_name)

class HouseDataset(Dataset):
    def __init__(self, df, image_folder, feature_extractor):
        self.df = df
        self.image_folder = image_folder
        self.feature_extractor = feature_extractor

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        image_path = os.path.join(self.image_folder, self.df.iloc[idx]["image_name"])
        image = Image.open(image_path).convert("RGB")
        inputs = self.feature_extractor(images=image, return_tensors="pt")
        label = torch.tensor(self.df.iloc[idx]["class"], dtype=torch.long)
        return {"pixel_values": inputs["pixel_values"].squeeze(), "labels": label}

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch32-384 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([2]) in the model instantiated
- classifier.weight: found shape torch.Size([1000, 768]) in the checkpoint and torch.Size([2, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(

In [ ]:
df = pd.read_csv("/kaggle/input/competitions/super-ai-engineer-season-6-individual-hackathon-house-recognition/train.csv")
image_folder = "/kaggle/input/competitions/super-ai-engineer-season-6-individual-hackathon-house-recognition/train/train"
dataset = HouseDataset(df, image_folder, feature_extractor)

In [ ]:
train_size = int(0.8 * len(dataset))
eval_size = len(dataset) - train_size
train_dataset, eval_dataset = random_split(dataset, [train_size, eval_size])

In [ ]:
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=4,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,  # Log progress every 10 steps
    report_to="none",
)

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [ ]:
from sklearn.metrics import accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = logits.argmax(axis=1)
    acc = accuracy_score(labels, predictions)
    return {"accuracy": acc}

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics  # 👈 เพิ่มตรงนี้
)

In [ ]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py:71: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(

TrainOutput(global_step=1184, training_loss=0.09955587032537379, metrics={'train_runtime': 539.5944, 'train_samples_per_second': 17.509, 'train_steps_per_second': 2.194, 'total_flos': 2.1949792915370803e+18, 'train_loss': 0.09955587032537379, 'epoch': 4.0})

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
def predict(images_folder, model, feature_extractor, device):
    model.eval()
    predictions = []
    image_files = [f for f in os.listdir(images_folder) if f.endswith(".jpg") or f.endswith(".png")]

    for image_file in image_files:
        image_path = os.path.join(images_folder, image_file)
        image = Image.open(image_path).convert("RGB")
        inputs = feature_extractor(images=image, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)
            predicted_label = torch.argmax(outputs.logits, dim=-1).item()
        predictions.append((image_file, predicted_label))

    return predictions

In [ ]:
test_folder = "/kaggle/input/competitions/super-ai-engineer-season-6-individual-hackathon-house-recognition/test/test"
predictions = predict(test_folder, model, feature_extractor,device)

In [ ]:
predictions

[('fd0900c0.jpg', 1),
 ('b17ced93.jpg', 0),
 ('5157729e.jpg', 1),
 ('9b25615e.jpg', 0),
 ('1df1da60.jpg', 0),
 ('43c5b7da.jpg', 1),
 ('7e90f408.jpg', 1),
 ('5f5ef892.jpg', 0),
 ('7e6cafaa.jpg', 1),
 ('4da96bd3.jpg', 1),
 ('4bc363dd.jpg', 0),
 ('d1b21893.jpg', 1),
 ('711bde86.jpg', 0),
 ('a5261896.jpg', 0),
 ('12c17ddf.jpg', 1),
 ('d18836ca.jpg', 1),
 ('57b3c5c2.jpg', 0),
 ('2d7181b5.jpg', 0),
 ('57200181.jpg', 1),
 ('41487df6.jpg', 1),
 ('c3726bb5.jpg', 0),
 ('c9d1a911.jpg', 0),
 ('5f033aaf.jpg', 1),
 ('4961b93c.jpg', 0),
 ('d1d12715.jpg', 1),
 ('beefc26e.jpg', 1),
 ('01ccbb76.jpg', 0),
 ('c37dbcf4.jpg', 0),
 ('35d7632c.jpg', 0),
 ('228369aa.jpg', 1),
 ('dfcba56a.jpg', 1),
 ('36cf3714.jpg', 0),
 ('7a920b80.jpg', 0),
 ('9bfc35a3.jpg', 1),
 ('f31a3abc.jpg', 1),
 ('4fd38ae5.jpg', 1),
 ('d8d67dcf.jpg', 1),
 ('0f198b7d.jpg', 0),
 ('c74652c2.jpg', 0),
 ('887f5c9f.jpg', 0),
 ('a799221f.jpg', 1),
 ('c336ce30.jpg', 1),
 ('39b8b3bb.jpg', 1),
 ('504c8cfe.jpg', 0),
 ('defe8dfd.jpg', 0),
 ('b6f685c7.jpg', 1),
 ('127f14ae.jpg', 0),
 ('30c45964.jpg', 1),
 ('f4d75b21.jpg', 0),
 ('2cb78ff7.jpg', 1),
 ('f19a558f.jpg', 1),
 ('21f0bc2e.jpg', 1),
 ('5165b88f.jpg', 0),
 ('bc2ed46a.jpg', 1),
 ('1481178a.jpg', 1),
 ('ac02f2ab.jpg', 1),
 ('d6c951a0.jpg', 0),
 ('a2067109.jpg', 1),
 ('7d51a6fc.jpg', 1),
 ('b41adb8e.jpg', 1),
 ('ec174460.jpg', 0),
 ('9b8b6867.jpg', 0),
 ('82da3ef8.jpg', 1),
 ('461acb3f.jpg', 0),
 ('d6207ea6.jpg', 0),
 ('9a74f200.jpg', 1),
 ('9c45ddb2.jpg', 1),
 ('bab459be.jpg', 0),
 ('fa2b940f.jpg', 0),
 ('332ded3f.jpg', 1),
 ('ea1b867d.jpg', 1),
 ('774f33a8.jpg', 0),
 ('848fa28e.jpg', 1),
 ('cc7ab727.jpg', 1),
 ('e8482e4d.jpg', 1),
 ('47237256.jpg', 1),
 ('005f930c.jpg', 0),
 ('8470632a.jpg', 0),
 ('f9a2a0c6.jpg', 1),
 ('3c4e06be.jpg', 1),
 ('89b0d845.jpg', 1),
 ('d1e2bf36.jpg', 1),
 ('3477f767.jpg', 0),
 ('9a9f6c5e.jpg', 1),
 ('e7a6955d.jpg', 1),
 ('e91bb2b8.jpg', 1),
 ('b1b16817.jpg', 0),
 ('c2ee6643.jpg', 1),
 ('3fe1c275.jpg', 1),
 ('81f26568.jpg', 0),
 ('b3b9a47b.jpg', 1),
 ('46979732.jpg', 0),
 ('a9e9d863.jpg', 1),
 ('7fd6caef.jpg', 1),
 ('ab45730f.jpg', 0),
 ('9084e219.jpg', 1),
 ('98768d3f.jpg', 1),
 ('ab1e40b9.jpg', 0),
 ('44913ee8.jpg', 0),
 ('74d21a05.jpg', 1),
 ('6cb6f1a0.jpg', 0),
 ('438791e2.jpg', 1),
 ('844130ad.jpg', 0),
 ('8ce5fd60.jpg', 0),
 ('5da44a16.jpg', 0),
 ('cd6227a6.jpg', 1),
 ('0a2aa274.jpg', 0),
 ('924a6a89.jpg', 1),
 ('2130e146.jpg', 1),
 ('8a60480c.jpg', 0),
 ('9d2d06c1.jpg', 0),
 ('d1f89f72.jpg', 1),
 ('1b691cea.jpg', 0),
 ('a956fc6f.jpg', 0),
 ('9214ae8f.jpg', 0),
 ('a5b8517e.jpg', 0),
 ('beb7d70b.jpg', 0),
 ('df36b626.jpg', 0),
 ('037f2425.jpg', 0),
 ('36591396.jpg', 1),
 ('58d343f2.jpg', 1),
 ('e03acd80.jpg', 1),
 ('96e84245.jpg', 1),
 ('582c787c.jpg', 0),
 ('ccc87a03.jpg', 0),
 ('ccd2b014.jpg', 0),
 ('7ca0a84e.jpg', 0),
 ('fcad7500.jpg', 0),
 ('53270b27.jpg', 1),
 ('ee1e2c20.jpg', 0),
 ('4e06021e.jpg', 1),
 ('128f0b37.jpg', 0),
 ('4131b295.jpg', 1),
 ('899293d5.jpg', 1),
 ('3f89997e.jpg', 1),
 ('bd64800e.jpg', 0),
 ('19838136.jpg', 0),
 ('a3859909.jpg', 1),
 ('c606c2f6.jpg', 0),
 ('d20acd55.jpg', 1),
 ('630ca612.jpg', 1),
 ('eda99fd4.jpg', 0),
 ('cbe2448a.jpg', 1),
 ('01ee5917.jpg', 0),
 ('1f0f2402.jpg', 0),
 ('e927a0e2.jpg', 1),
 ('558219e2.jpg', 0),
 ('c6d98a5a.jpg', 0),
 ('be60a90d.jpg', 0),
 ('71032a54.jpg', 0),
 ('a3f61e9f.jpg', 1),
 ('2c6adef4.jpg', 1),
 ('a2e57b4d.jpg', 1),
 ('b1c67ce9.jpg', 1),
 ('7a57fa54.jpg', 0),
 ('120e9ae8.jpg', 1),
 ('aa9d5db0.jpg', 0),
 ('e1252655.jpg', 0),
 ('e57009e7.jpg', 1),
 ('b70954f3.jpg', 0),
 ('5754a281.jpg', 1),
 ('95fea609.jpg', 1),
 ('3ec07958.jpg', 0),
 ('185c58d3.jpg', 1),
 ('45ccb09a.jpg', 1),
 ('c1284296.jpg', 0),
 ('a1b86d28.jpg', 1),
 ('fc51a3cb.jpg', 1),
 ('065def68.jpg', 0),
 ('19f955db.jpg', 0),
 ('76d68031.jpg', 0),
 ('428f57e8.jpg', 1),
 ('b0c5d90a.jpg', 1),
 ('d875b6d9.jpg', 0),
 ('dd40c31b.jpg', 0),
 ('0cc48828.jpg', 1),
 ('c4e0b2d3.jpg', 1),
 ('29dce285.jpg', 1),
 ('8b1ce347.jpg', 0),
 ('828d7d35.jpg', 0),
 ('2e93f5b4.jpg', 1),
 ('9f8950de.jpg', 0),
 ('d011d8c4.jpg', 1),
 ('8e40c4be.jpg', 0),
 ('8f81b246.jpg', 0),
 ('e0370240.jpg', 1),
 ('5187b8e7.jpg', 0),
 ('8634cb83.jpg', 0),
 ('597df2f7.jpg', 0),
 ('e89ee007.jpg', 1),
 ('b55400a2.jpg', 0),
 ('a32d2442.jpg', 0),
 ('7f6c2638.jpg', 0),
 ('8b2e783f.jpg', 0),
 ('e4b420b0.jpg', 0),
 ('2e1dc703.jpg', 0),
 ('9fa6c971.jpg', 1),
 ('f1288f71.jpg', 1),
 ('4f41c4fc.jpg', 0),
 ('9a99e2e3.jpg', 1),
 ('71dd0a48.jpg', 1),
 ('5c421eed.jpg', 1),
 ('e4267abb.jpg', 0),
 ('9dec333f.jpg', 0),
 ('683d8605.jpg', 0),
 ('b69f38f2.jpg', 0),
 ('3915383f.jpg', 0),
 ('8d3c183a.jpg', 1),
 ('0561ab5a.jpg', 1),
 ('897e6108.jpg', 1),
 ('2053fdd8.jpg', 0),
 ('340a3e9d.jpg', 1),
 ('44f72a5f.jpg', 1),
 ('d6dd6ec9.jpg', 1),
 ('9d9b2036.jpg', 1),
 ('569cb738.jpg', 0),
 ('2f008da4.jpg', 0),
 ('9a3e6aff.jpg', 0),
 ('087c9dbe.jpg', 0),
 ('187e9afa.jpg', 0),
 ('bf17d933.jpg', 0),
 ('400469e8.jpg', 0),
 ('aa00a70f.jpg', 1),
 ('656fc174.jpg', 0),
 ('2c45d334.jpg', 0),
 ('3087825c.jpg', 0),
 ('8c968c1c.jpg', 0),
 ('91a9eca6.jpg', 0),
 ('f0949a41.jpg', 1),
 ('8abeb5d0.jpg', 0),
 ('d97916a0.jpg', 1),
 ('401c74d1.jpg', 1),
 ('735dfd16.jpg', 1),
 ('f0cc66f6.jpg', 1),
 ('bfaf7b24.jpg', 1),
 ('9faef6d1.jpg', 1),
 ('06e9b35d.jpg', 0),
 ('c96b78f5.jpg', 1),
 ('d3f19bd2.jpg', 1),
 ('e85f01f4.jpg', 1),
 ('1310e8df.jpg', 0),
 ('51c109e4.jpg', 0),
 ('be6b83c5.jpg', 1),
 ('15c65f1a.jpg', 1),
 ('1888de25.jpg', 1),
 ('4e30547a.jpg', 0),
 ('04c3f1bd.jpg', 0),
 ('0b8885ec.jpg', 0),
 ('a0faaf76.jpg', 1),
 ('9ea71b8b.jpg', 1),
 ('ecc33630.jpg', 1),
 ('f19fc697.jpg', 0),
 ('d30d00ed.jpg', 1),
 ('f157aa5d.jpg', 1),
 ('78922849.jpg', 0),
 ('ee411bf6.jpg', 1),
 ('5d82d2b1.jpg', 1),
 ('f96bd02a.jpg', 0),
 ('042d74d8.jpg', 1),
 ('6bc4b3e7.jpg', 0),
 ('64bb87d7.jpg', 1),
 ('fc6a7fec.jpg', 0),
 ('832900d5.jpg', 0),
 ('6ba3e83e.jpg', 1),
 ('575ec55a.jpg', 1),
 ('914e0e23.jpg', 1),
 ('0812bf3e.jpg', 1),
 ('bc5aae3a.jpg', 1),
 ('3dc31ceb.jpg', 1),
 ('3608ab19.jpg', 1),
 ('16d1ce9d.jpg', 0),
 ('79109903.jpg', 1),
 ('e026753e.jpg', 1),
 ('b9db66f8.jpg', 0),
 ('90ea2194.jpg', 1),
 ('34064367.jpg', 0),
 ('683ac559.jpg', 1),
 ('fd6a752a.jpg', 1),
 ('4f5b08b1.jpg', 1),
 ('cddbcc07.jpg', 1),
 ('47975e30.jpg', 0),
 ('f2a3e355.jpg', 1),
 ('728caeea.jpg', 0),
 ('8cd4979e.jpg', 0),
 ('dfd0876d.jpg', 0),
 ('7eeee8e1.jpg', 0),
 ('4168797f.jpg', 1),
 ('5fb482dc.jpg', 1),
 ('72454909.jpg', 0),
 ('06b15de3.jpg', 1),
 ('fa1c92f7.jpg', 0),
 ('8582f6c4.jpg', 0),
 ('17037193.jpg', 0),
 ('7df1d7e9.jpg', 1),
 ('b8f7b417.jpg', 1),
 ('767b278e.jpg', 1),
 ('aaa91779.jpg', 1),
 ('1d145a7e.jpg', 0),
 ('baf16c49.jpg', 0),
 ('a6154645.jpg', 0),
 ('3cb37eb1.jpg', 0),
 ('a8d4d78b.jpg', 1),
 ('ef82fea8.jpg', 0),
 ('a352d477.jpg', 0),
 ('00a98706.jpg', 0),
 ('8dc1516a.jpg', 0),
 ('ad6a7967.jpg', 1),
 ('c6047c76.jpg', 0),
 ('eaca09f4.jpg', 1),
 ('6a3448d9.jpg', 0),
 ('741a02b2.jpg', 1),
 ('5913e805.jpg', 1),
 ('4447529e.jpg', 0),
 ('ad987cbe.jpg', 1),
 ('8789fe5d.jpg', 0),
 ('b3f0f04b.jpg', 1),
 ('caf9eec7.jpg', 1),
 ('216d63f1.jpg', 1),
 ('e16354aa.jpg', 1),
 ('d4d5efbe.jpg', 1),
 ('86175aa8.jpg', 0),
 ('09127206.jpg', 1),
 ('dce236ac.jpg', 1),
 ('de64afe0.jpg', 0),
 ('7c5d7eb9.jpg', 1),
 ('f711c1fb.jpg', 0),
 ('d933e0f5.jpg', 0),
 ('75e18fe0.jpg', 1),
 ('74750a38.jpg', 1),
 ('8df7aec6.jpg', 1),
 ('d54b10db.jpg', 0),
 ('a3c844f1.jpg', 0),
 ('24413046.jpg', 0),
 ('6110be70.jpg', 0),
 ('ab1ed995.jpg', 0),
 ('c24fd556.jpg', 0),
 ('9a38df21.jpg', 0),
 ('004c4789.jpg', 0),
 ('299c8726.jpg', 1),
 ('b510aaf0.jpg', 1),
 ('7efe714e.jpg', 0),
 ('2f670aed.jpg', 1),
 ('2d6bbae3.jpg', 0),
 ('20cf749e.jpg', 1),
 ('969e4be8.jpg', 0),
 ('00eac2a3.jpg', 1),
 ('75311361.jpg', 0),
 ('3ff35c60.jpg', 0),
 ('49e19ea0.jpg', 0),
 ('50664e5f.jpg', 1),
 ('0b5cd147.jpg', 0),
 ('73bd7d72.jpg', 1),
 ('67e60873.jpg', 1),
 ('9b172082.jpg', 1),
 ('27096e35.jpg', 0),
 ('dc648f14.jpg', 1),
 ('6f62887b.jpg', 1),
 ('413b93ff.jpg', 1),
 ('c099a9a0.jpg', 0),
 ('6bf3a0f7.jpg', 1),
 ('bac653b4.jpg', 0),
 ('a55e9e83.jpg', 1),
 ('1149eb32.jpg', 0),
 ('ed3719a5.jpg', 1),
 ('cca5ae46.jpg', 0),
 ('eae0945a.jpg', 0),
 ('af3c50f6.jpg', 0),
 ('aaea811c.jpg', 0),
 ('af393f0c.jpg', 1),
 ('4e2d8fef.jpg', 0),
 ('e082c75d.jpg', 0),
 ('1aa8fd7f.jpg', 1),
 ('27102e59.jpg', 1),
 ('e69c40e0.jpg', 0),
 ('67b8782e.jpg', 0),
 ('adb7e97b.jpg', 1),
 ('b002487d.jpg', 0),
 ('beac498c.jpg', 0),
 ('814b66b1.jpg', 1),
 ('f374a94a.jpg', 0),
 ('20fe74fb.jpg', 1),
 ('dec0f1e2.jpg', 1),
 ('15b9f115.jpg', 1),
 ('9db2bde8.jpg', 1),
 ('81fb9fd7.jpg', 1),
 ('67d766d2.jpg', 1),
 ('abfa2a8f.jpg', 0),
 ('29a50f92.jpg', 0),
 ('f5f5e913.jpg', 1),
 ('33c1c186.jpg', 0),
 ('6ebe19dd.jpg', 1),
 ('f8c3609c.jpg', 1),
 ('302728e8.jpg', 1),
 ('b76786bd.jpg', 0),
 ('db935849.jpg', 1),
 ('d33b6c1c.jpg', 1),
 ('e464e9f0.jpg', 1),
 ('00da9dd7.jpg', 1),
 ('791982df.jpg', 0),
 ('e96cef2b.jpg', 1),
 ('a51d7182.jpg', 0),
 ('0fb8776e.jpg', 0),
 ('25b85661.jpg', 0),
 ('917771ce.jpg', 0),
 ('8176d497.jpg', 1),
 ('75babc9b.jpg', 1),
 ('f2f311f0.jpg', 0),
 ('10eb0b77.jpg', 0),
 ('87c285bc.jpg', 0),
 ('b7aeafc6.jpg', 0),
 ('2fe4a495.jpg', 0),
 ('cba2af51.jpg', 0),
 ('d90dbf37.jpg', 0),
 ('8179b213.jpg', 0),
 ('a4418dbf.jpg', 0),
 ('c596c93c.jpg', 1),
 ('e0eb1696.jpg', 0),
 ('87f0034a.jpg', 0),
 ('d05f85bb.jpg', 1),
 ('529de7b1.jpg', 0),
 ('21edc12d.jpg', 1),
 ('c1eb81b4.jpg', 0),
 ('45cf537e.jpg', 1),
 ('f1e5d780.jpg', 0),
 ('38c26968.jpg', 0),
 ('e0462caa.jpg', 0),
 ('50cd3d25.jpg', 0),
 ('ce327b46.jpg', 0),
 ('0a5dcd96.jpg', 0),
 ('7b5e37f5.jpg', 1),
 ('14197516.jpg', 1),
 ('42749a03.jpg', 1),
 ('bc0e5b55.jpg', 0),
 ('9696d4b0.jpg', 1),
 ('48364c8b.jpg', 1),
 ('b6474da2.jpg', 0),
 ('b04e2a06.jpg', 0),
 ('143de759.jpg', 1),
 ('ccc59b72.jpg', 1),
 ('1950fb7b.jpg', 0),
 ('25d9c5c0.jpg', 0),
 ('8bcfc0d2.jpg', 0),
 ('b1027137.jpg', 1),
 ('34e65477.jpg', 0),
 ('d19b4740.jpg', 1),
 ('6ee716ef.jpg', 0),
 ('4127fedf.jpg', 0),
 ('4a466c49.jpg', 0),
 ('d5766643.jpg', 1),
 ('d5461e01.jpg', 1),
 ('3e11375b.jpg', 0),
 ('3a6c80a3.jpg', 1),
 ('16173ced.jpg', 0),
 ('7cedad8c.jpg', 1),
 ('c2ccbdad.jpg', 1),
 ('6506717c.jpg', 0),
 ('4fae3445.jpg', 1),
 ('f291c68a.jpg', 1),
 ('12dbebf8.jpg', 0),
 ('d6f7f529.jpg', 1),
 ('7a101d27.jpg', 0),
 ('bdf217f5.jpg', 1),
 ('89d47be9.jpg', 0),
 ('e0f8b602.jpg', 1),
 ('ec908e75.jpg', 1),
 ('73ab6cfc.jpg', 0),
 ('3108b4db.jpg', 1),
 ('6387d951.jpg', 1),
 ('3db514a7.jpg', 0),
 ('b1c66306.jpg', 0),
 ('d17a09eb.jpg', 0),
 ('d9ca5d5f.jpg', 1),
 ('d24d8e4b.jpg', 0),
 ('0e4f73ba.jpg', 1),
 ('30d75ac4.jpg', 0),
 ('3183d69f.jpg', 1),
 ('5e04ee4a.jpg', 0),
 ('ca4be818.jpg', 1),
 ('d0c3811c.jpg', 1),
 ('53626eb3.jpg', 0),
 ('f060bc41.jpg', 1),
 ('9efd3e9d.jpg', 1),
 ('0b774419.jpg', 1),
 ('b9a97231.jpg', 1),
 ('9fa1ecd6.jpg', 1),
 ('d943e0c8.jpg', 0),
 ('c25c7fbf.jpg', 0),
 ('32f9963a.jpg', 0),
 ('2073ad7f.jpg', 0),
 ('7b304617.jpg', 0),
 ('ed72fd6c.jpg', 1),
 ('c2827204.jpg', 0),
 ('187a8338.jpg', 0),
 ('e122901f.jpg', 1),
 ('5923d103.jpg', 1),
 ('2efc53fd.jpg', 0),
 ('ca503ddb.jpg', 0),
 ('d41d2a8b.jpg', 1),
 ('8b06b40f.jpg', 0),
 ('61bac937.jpg', 0),
 ('7d7a3d8c.jpg', 0),
 ('2e1cb076.jpg', 1),
 ('e2607cb9.jpg', 1),
 ('e2a8da09.jpg', 0),
 ('de46dae2.jpg', 1),
 ('74ad8c45.jpg', 1),
 ('7787dbaa.jpg', 1),
 ('85e6ac9a.jpg', 1),
 ('15b0e8c6.jpg', 1),
 ('4b711eea.jpg', 0),
 ('9f6d8757.jpg', 0),
 ('0d0556a3.jpg', 0),
 ('32d34d03.jpg', 0),
 ('6aebd62e.jpg', 1),
 ('29948715.jpg', 0),
 ('156459cf.jpg', 0),
 ('98bd060e.jpg', 0),
 ('45d1d0da.jpg', 0),
 ('82de2aa1.jpg', 1),
 ('a0d1d53a.jpg', 0),
 ('5e0166f8.jpg', 1),
 ('632726ba.jpg', 1),
 ('97020557.jpg', 0),
 ('01265567.jpg', 0),
 ('f33d6a9a.jpg', 1),
 ('caf03c44.jpg', 1),
 ('3cfb57dc.jpg', 1),
 ('67bd97de.jpg', 0),
 ('2b4a905c.jpg', 0),
 ('3cb7e6f8.jpg', 1),
 ('cf90a416.jpg', 0),
 ('e48208b3.jpg', 0),
 ('7ba62bd4.jpg', 0),
 ('35173e73.jpg', 1),
 ('4c4ec5c3.jpg', 1),
 ('de97e1a9.jpg', 1),
 ('ae089c2f.jpg', 0),
 ('9341c391.jpg', 1),
 ('9d779855.jpg', 1),
 ('35b3a93e.jpg', 0),
 ('32e72801.jpg', 1),
 ('412a13ac.jpg', 0),
 ('593f5feb.jpg', 1),
 ('088aa66b.jpg', 1),
 ('906ff37c.jpg', 1),
 ('954d962f.jpg', 1),
 ('193cad70.jpg', 0),
 ('5aca8314.jpg', 1),
 ('0188f57d.jpg', 0),
 ('32e02d2f.jpg', 0),
 ('d92834e8.jpg', 1),
 ('34d23cb6.jpg', 1),
 ('3c307a4a.jpg', 0),
 ('4367bd45.jpg', 0),
 ('aa0e011b.jpg', 1),
 ('08f0d385.jpg', 1),
 ('ee8b7229.jpg', 1),
 ('449b791c.jpg', 0),
 ('97e3d015.jpg', 1),
 ('b6d0e5d0.jpg', 0),
 ('4c2d4132.jpg', 0),
 ('1afeaf2e.jpg', 0),
 ('1f97a7db.jpg', 1),
 ('5cf0912c.jpg', 0),
 ('7c6b0b7a.jpg', 0),
 ('63ce4369.jpg', 0),
 ('009095e8.jpg', 0),
 ('e1484aff.jpg', 0),
 ('0e7672cd.jpg', 0),
 ('da030043.jpg', 0),
 ('eb8d55bb.jpg', 0),
 ('8e999410.jpg', 0),
 ('2c80c176.jpg', 0),
 ('737506e9.jpg', 0),
 ('9dce64a6.jpg', 1),
 ('df8062b8.jpg', 0),
 ('04dd10ad.jpg', 0),
 ('a1bb6c6f.jpg', 1),
 ('0f87ff9d.jpg', 1),
 ('58267211.jpg', 1),
 ('c8fd841f.jpg', 1),
 ('1f5a3338.jpg', 1),
 ('53c9a58f.jpg', 1),
 ('0fe6eea4.jpg', 0),
 ('08f5101e.jpg', 1),
 ('00e2bfe0.jpg', 0),
 ('e035ad5b.jpg', 1),
 ('0a39e715.jpg', 0),
 ('b5a13387.jpg', 0),
 ('da258189.jpg', 0),
 ('07b131dd.jpg', 0),
 ('3f07beda.jpg', 0),
 ('2b3d31e5.jpg', 0),
 ('781c193c.jpg', 0),
 ('87d9797d.jpg', 1),
 ('656e8851.jpg', 1),
 ('635b361b.jpg', 0),
 ('d4b83208.jpg', 1),
 ('36e9394a.jpg', 1),
 ('7e092106.jpg', 0),
 ('21fd7803.jpg', 1),
 ('db02e30d.jpg', 0),
 ('01f9d203.jpg', 1),
 ('7bb02ebb.jpg', 0),
 ('53d31435.jpg', 0),
 ('c8658c7f.jpg', 0),
 ('ab1d372e.jpg', 1),
 ('90b17e73.jpg', 0),
 ('17cd0dab.jpg', 0),
 ('4337ff85.jpg', 0),
 ('f5b0b1c2.jpg', 1),
 ('acd08c44.jpg', 0),
 ('0acafaac.jpg', 1),
 ('b14a2f05.jpg', 1),
 ('64bb2834.jpg', 0),
 ('d4663719.jpg', 1),
 ('be593352.jpg', 1),
 ('fe652827.jpg', 0),
 ('f0d58c23.jpg', 1),
 ('9d167923.jpg', 0),
 ('9e4334b4.jpg', 0),
 ('15d8ccc1.jpg', 1),
 ('5fe420e8.jpg', 1),
 ('54466b30.jpg', 0),
 ('81bc175f.jpg', 0),
 ('95ee6fe9.jpg', 1),
 ('429089c0.jpg', 1),
 ('c346950c.jpg', 1),
 ('6cee5846.jpg', 1),
 ('68156078.jpg', 0),
 ('5ad77b0a.jpg', 0),
 ('01945b53.jpg', 0),
 ('f6795928.jpg', 1),
 ('087b0641.jpg', 1),
 ('5af5198a.jpg', 0),
 ('e7e40569.jpg', 1),
 ('dcf84e2c.jpg', 1),
 ('35d31cce.jpg', 1),
 ('adacf01e.jpg', 0),
 ('3c953d4e.jpg', 0),
 ('74ce4676.jpg', 0),
 ('4724272d.jpg', 1),
 ('07a3abdf.jpg', 0),
 ('c85c039f.jpg', 1),
 ('8c31d467.jpg', 0),
 ('4ebdce76.jpg', 1),
 ('f79a5538.jpg', 0),
 ('d7564109.jpg', 0),
 ('ae71ea5b.jpg', 0),
 ('169370f5.jpg', 1),
 ('78c097a0.jpg', 1),
 ('2d58278a.jpg', 1),
 ('de9788ab.jpg', 1),
 ('98873a6d.jpg', 0),
 ('57b2ae82.jpg', 1),
 ('33e4ec9b.jpg', 0),
 ('3e5a0ca6.jpg', 0),
 ('3369298d.jpg', 1),
 ('b95928d0.jpg', 1),
 ('1c057660.jpg', 1),
 ('270b0869.jpg', 1),
 ('533843b6.jpg', 0),
 ('7a44c39b.jpg', 1),
 ('063aa843.jpg', 1),
 ('ed4a00c7.jpg', 1),
 ('f7fb7b15.jpg', 1),
 ('5d2293a9.jpg', 1),
 ('9e1de42c.jpg', 0),
 ('82402242.jpg', 0),
 ('d62ac512.jpg', 0),
 ('1bd5fea5.jpg', 0),
 ('fc32f09c.jpg', 1),
 ('54f26e6b.jpg', 1),
 ('f6c9c731.jpg', 0),
 ('5094a9c7.jpg', 0),
 ('e7c48842.jpg', 0),
 ('6535e588.jpg', 1),
 ('fdfa58fe.jpg', 0),
 ('9d30bc51.jpg', 1),
 ('6873f22d.jpg', 1),
 ('8eab133b.jpg', 0),
 ('16321b38.jpg', 0),
 ('99fab84f.jpg', 0),
 ('a5df00e4.jpg', 0),
 ('a8dbcd52.jpg', 1),
 ('2f31ffc0.jpg', 0),
 ('e056f1f9.jpg', 1),
 ('2780944d.jpg', 0),
 ('89216483.jpg', 0),
 ('7bd7b92f.jpg', 0),
 ('52d29a7c.jpg', 1),
 ('a232de2f.jpg', 0),
 ('4885c8a1.jpg', 0),
 ('8623c63c.jpg', 1),
 ('34330495.jpg', 1),
 ('4d1b8a1e.jpg', 0),
 ('087f7050.jpg', 1),
 ('b3df6371.jpg', 1),
 ('69c0ed63.jpg', 1),
 ('a3a5b050.jpg', 0),
 ('05f824ae.jpg', 0),
 ('40a35a5c.jpg', 1),
 ('0e7bf631.jpg', 0),
 ('6121332d.jpg', 0),
 ('b2864a5f.jpg', 0),
 ('60bb9abd.jpg', 1),
 ('1c4f9313.jpg', 0),
 ('b26f3fa8.jpg', 1),
 ('e851fb72.jpg', 0),
 ('ed6248a0.jpg', 0),
 ('5ea84627.jpg', 1),
 ('38cee806.jpg', 0),
 ('33416bc2.jpg', 1),
 ('12eb4d3f.jpg', 0),
 ('d75fb466.jpg', 1),
 ('f4c92a8d.jpg', 0),
 ('df12288f.jpg', 1),
 ('9736ac21.jpg', 1),
 ('800205bd.jpg', 0),
 ('11d6e00c.jpg', 0),
 ('4dd4334c.jpg', 0),
 ('acce0323.jpg', 0),
 ('1b8d4f5a.jpg', 1),
 ('cbdf3524.jpg', 1),
 ('c33c19b1.jpg', 0),
 ('e0d17db9.jpg', 1),
 ('18a79674.jpg', 0),
 ('26d5aa1f.jpg', 0),
 ('73729abb.jpg', 0),
 ('4cd45008.jpg', 0),
 ('28ca6b22.jpg', 0),
 ('6f4c6ad6.jpg', 1),
 ('afe3bb15.jpg', 1),
 ('48e796bc.jpg', 0),
 ('d7f73903.jpg', 0),
 ('d3c57931.jpg', 0),
 ('5480493c.jpg', 0),
 ('c480551d.jpg', 1),
 ('342de140.jpg', 0),
 ('12fa2b23.jpg', 0),
 ('e24420c1.jpg', 0),
 ('806357e2.jpg', 1),
 ('0f12067f.jpg', 1),
 ('e8433345.jpg', 1),
 ('254f3c01.jpg', 1),
 ('60080d3e.jpg', 1),
 ('d73c28f1.jpg', 0),
 ('94cdd6da.jpg', 0),
 ('8917f559.jpg', 0),
 ('f169dcd4.jpg', 1),
 ('f5c8ea3c.jpg', 0),
 ('4ff77183.jpg', 0),
 ('545e632d.jpg', 1),
 ('4dd7beb9.jpg', 0),
 ('78821031.jpg', 1),
 ('64db070d.jpg', 0),
 ('c2269bf0.jpg', 0),
 ('32ac8ff2.jpg', 0),
 ('ae53a6a5.jpg', 1),
 ('4d369b4f.jpg', 0),
 ('b6c39fe7.jpg', 1),
 ('ea0fca13.jpg', 0),
 ('9909c6b0.jpg', 1),
 ('056fda9b.jpg', 0),
 ('d3b5ea13.jpg', 0),
 ('1e98c362.jpg', 0),
 ('480adb36.jpg', 1),
 ('ebbe548e.jpg', 0),
 ('d11bcf44.jpg', 1),
 ('2930ea03.jpg', 1),
 ('6e0cabd5.jpg', 1),
 ('b6399423.jpg', 0),
 ('ce27fd73.jpg', 0),
 ('754a112d.jpg', 1),
 ('94c28072.jpg', 0),
 ('d7678327.jpg', 0),
 ('fe0b78cb.jpg', 0),
 ('ec045077.jpg', 0),
 ('fdd34996.jpg', 1),
 ('75fe04de.jpg', 0),
 ('d884d1a7.jpg', 1),
 ('a8d6a155.jpg', 0),
 ('0059b42f.jpg', 1),
 ('93e4715c.jpg', 0),
 ('fa7cd05d.jpg', 0),
 ('f084bb31.jpg', 0),
 ('a255ac7f.jpg', 0),
 ('9c4f6921.jpg', 1),
 ('2625cc65.jpg', 1),
 ('5994b592.jpg', 0),
 ('c181d1ec.jpg', 0),
 ('a86bd98b.jpg', 0),
 ('67e39825.jpg', 0),
 ('7ba6d581.jpg', 0),
 ('afab7a60.jpg', 0),
 ('c1f7b4f6.jpg', 1),
 ('c87aa242.jpg', 0),
 ('73af8711.jpg', 0),
 ('18c038e1.jpg', 1),
 ('dbcacd86.jpg', 1),
 ('51e20a5d.jpg', 1),
 ('0d553e27.jpg', 1),
 ('880dfb48.jpg', 0),
 ('25ab6a5b.jpg', 1),
 ('15c7474b.jpg', 0),
 ('6a4a2b23.jpg', 0),
 ('116009f6.jpg', 0),
 ('ae174749.jpg', 1),
 ('3596294e.jpg', 0),
 ('2ac79bf3.jpg', 1),
 ('1ede07db.jpg', 1),
 ('8ba702ed.jpg', 1),
 ('7ff8da4e.jpg', 0),
 ('b55338e0.jpg', 1),
 ('7e8862e8.jpg', 0),
 ('194f1303.jpg', 0),
 ('05a12031.jpg', 1),
 ('f2045e14.jpg', 0),
 ('397ba7da.jpg', 1),
 ('30213569.jpg', 1),
 ('b0428960.jpg', 1),
 ('96601579.jpg', 0),
 ('07be23b3.jpg', 0),
 ('d5fc6628.jpg', 0),
 ('227cebf5.jpg', 0),
 ('0583f945.jpg', 0),
 ('6d626e6c.jpg', 0),
 ('96e0e062.jpg', 1),
 ('ab14b28a.jpg', 0),
 ('b0b8958e.jpg', 0),
 ('f604674e.jpg', 0),
 ('6eff7b85.jpg', 1),
 ('8adf335a.jpg', 1),
 ('84988add.jpg', 1),
 ('3124b30c.jpg', 0),
 ('dee9804e.jpg', 0),
 ('ec200664.jpg', 0),
 ('f9175d84.jpg', 0),
 ('7db761d4.jpg', 0),
 ('d0f7b2f9.jpg', 1),
 ('b0c973c3.jpg', 1),
 ('ba58e2a0.jpg', 0),
 ('673b02ea.jpg', 0),
 ('8ed6a7b5.jpg', 1),
 ('cb41bd82.jpg', 0),
 ('2f2d3193.jpg', 0),
 ('6f01272a.jpg', 1),
 ('d7b36593.jpg', 0),
 ('4c8086b6.jpg', 0),
 ('fbb813d0.jpg', 1),
 ('98df3c66.jpg', 1),
 ('7c112068.jpg', 0),
 ('d664aa29.jpg', 0),
 ('699296dc.jpg', 0),
 ('4cf06860.jpg', 0),
 ('8779fdb4.jpg', 0),
 ('76bae481.jpg', 0),
 ('470c78b3.jpg', 0),
 ('8ef5370d.jpg', 0),
 ('54d1ba78.jpg', 0),
 ('8e3ae715.jpg', 1),
 ('6301b5ad.jpg', 1),
 ('d993e17a.jpg', 1),
 ('7f90ee2c.jpg', 0),
 ('1a03c450.jpg', 1),
 ('97946f3d.jpg', 1),
 ('546a0935.jpg', 1),
 ('c8448a94.jpg', 0),
 ('6e32a8c0.jpg', 0),
 ('ff614c14.jpg', 1),
 ('7ec1365e.jpg', 1),
 ('aea73d4c.jpg', 1),
 ('cc13f6f4.jpg', 1),
 ('6a879f71.jpg', 0),
 ('09056569.jpg', 1),
 ('051dd1f5.jpg', 0),
 ('d4d23a5d.jpg', 1),
 ('8e379a63.jpg', 1),
 ('c95e1a8a.jpg', 0),
 ('acb89d9c.jpg', 0),
 ('2a462bd8.jpg', 0),
 ('d9d7736c.jpg', 0),
 ('b625bbf8.jpg', 1),
 ('8e8467e9.jpg', 0),
 ('35c37bfb.jpg', 1),
 ('e6fddf67.jpg', 1),
 ('8ddd81b8.jpg', 0),
 ('88bb2b03.jpg', 0),
 ('fb45b847.jpg', 1),
 ('e5190015.jpg', 0),
 ('1e91e306.jpg', 0),
 ('f60c0635.jpg', 0),
 ('0f5b72ab.jpg', 1),
 ('ce937c2f.jpg', 0),
 ('9383fc3f.jpg', 1),
 ('6a5a68ee.jpg', 0),
 ('bbb92d47.jpg', 0),
 ('53b7d8b1.jpg', 0),
 ('69e54e88.jpg', 0),
 ('d7afe91d.jpg', 1),
 ('b965e3aa.jpg', 1),
 ('45ae4ec2.jpg', 1),
 ('418d34a5.jpg', 1),
 ('9e836a3c.jpg', 1),
 ('e96dcb75.jpg', 0),
 ('6feb260e.jpg', 0),
 ('30918ce5.jpg', 1),
 ('0338f3c6.jpg', 1),
 ('f5a603e1.jpg', 1),

In [ ]:
submit = pd.read_csv("/kaggle/input/competitions/super-ai-engineer-season-6-individual-hackathon-house-recognition/sample_submission.csv")

In [ ]:
submit

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

            id  answer
0     e4b420b0     0.0
1     23efa479     0.0
2     1f0f2402     0.0
3     8a60480c     NaN
4     11f20127     NaN
...        ...     ...
1545  ed44ac4d     NaN
1546  a2067109     NaN
1547  1481178a     NaN
1548  340a3e9d     NaN
1549  af393f0c     NaN

[1550 rows x 2 columns]

In [ ]:
ss = pd.DataFrame(predictions)

In [ ]:
ss = ss.rename(columns={0: "id", 1: "answer"})
ss["id"] = ss["id"].str.replace(".jpg", "")

In [ ]:
submit = submit.set_index("id")
ss = ss.set_index("id")
df_sorted = ss.reindex(submit.index)

In [ ]:
df_sorted

          answer
id
e4b420b0       0
23efa479       0
1f0f2402       0
8a60480c       0
11f20127       0
...          ...
ed44ac4d       1
a2067109       1
1481178a       1
340a3e9d       1
af393f0c       1

[1550 rows x 1 columns]

In [ ]:
df_sorted.to_csv("submit_house.csv")