In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import json
from PIL import Image
import os

In [2]:
#!unzip super-ai-engineer-ss-6-thai-language-image-captioning.zip

# preprocessing data

In [3]:
#create validation caption
with open("capgen_v1.0_val.json", "r", encoding="utf-8") as file:
    data_val = json.load(file)

# Convert JSON to a list of tuples (image_path, index, caption)
records = []
for image_path, captions in data_val.items():
    for idx, caption in enumerate(captions):
        records.append((image_path, idx, caption))

# Create DataFrame
caption_val = pd.DataFrame(records, columns=["image_path", "caption_index", "caption_text"])

In [4]:
#create training caption
with open("capgen_v1.0_train.json", "r", encoding="utf-8") as file:
    data_train = json.load(file)

# Convert JSON to a list of tuples (image_path, index, caption)
records = []
for image_path, captions in data_train.items():
    for idx, caption in enumerate(captions):
        records.append((image_path, idx, caption))

# Create DataFrame
caption_train = pd.DataFrame(records, columns=["image_path", "caption_index", "caption_text"])

In [5]:
#img = Image.open(image_path)
caption_train['from'] = caption_train["image_path"].apply(lambda x: x.split('/')[0])
caption_train['img_id'] = caption_train["image_path"].apply(lambda x: x.split('/')[-1])

In [6]:
caption_train

,image_path,caption_index,caption_text,from,img_id
0,coco/train2017/000000373716.jpg,0,ผู้หญิงสวมเสื้อแขนยาวสีขาวและเด็กนั่งเล่นกับสุ...,coco,000000373716.jpg
1,coco/train2017/000000373716.jpg,1,สาวคนนึงกำลังพาเด็กมานั่งเล่นอยู่ภายในสนามหญ้า...,coco,000000373716.jpg
2,coco/train2017/000000373716.jpg,2,ภาพขาวดำ ผู้หญิงนั่งบนพื้นอุ้มเด็กบนตัก ข้าง ๆ...,coco,000000373716.jpg
3,coco/train2017/000000196888.jpg,0,สีน้ำตาลตัวเล็กกำลังกินอาหารอยู่บนจานกระดาษสีข...,coco,000000196888.jpg
4,coco/train2017/000000196888.jpg,1,นกน้อยตัวหนึ่งกำลังจิกกินเศษอาหารที่วางทิ้งไว้...,coco,000000196888.jpg
...,...,...,...,...,...
430280,ipu24/train/food/28002.jpg,1,ขนมสับปะรดที่ใส่หมูสับใส่ในจานสีขาวและมีผักสวน...,ipu24,28002.jpg
430281,ipu24/train/food/28002.jpg,2,ในจานสีขาวมีสับปะรดหั่นเป็นชิ้นสามเหลี่ยมเล็ก ...,ipu24,28002.jpg
430282,ipu24/train/food/28003.jpg,0,ปลาดุกย่างเสียบไม้หลายตัวตั้งอยู่ในถาดมีผักแช่...,ipu24,28003.jpg
430283,ipu24/train/food/28003.jpg,1,ปลาดุกปิ้งจำนวนมากที่วางอยู่ในถาดอะลูมิเนียมทร...,ipu24,28003.jpg
430284,ipu24/train/food/28003.jpg,2,ปลาดุกย่างหลายตัวเสียบไม้วางอยู่บนตะแกรงที่มีถ...,ipu24,28003.jpg

In [7]:
caption_train_sub = caption_train[caption_train['caption_index']==0]
caption_train_sub = caption_train[caption_train['from']=='ipu24']

In [8]:
caption_train_sub = caption_train_sub.drop('caption_index', axis=1)
caption

'ปลาดุกย่างหลายตัวเสียบไม้วางอยู่บนตะแกรงที่มีถาดรองและด้านหน้ามีกะละมังที่แช่สะเดา'

In [9]:
caption_train_sub['from'].value_counts()

from
ipu24    85241
Name: count, dtype: int64

In [10]:
import os
import pandas as pd
from tqdm import tqdm  # Import tqdm for progress bar

# Function to load a single image based on row info
def load_image(row):
    # Define the base path for each source type
    if row['from'] == 'ipu24':
        if row['image_path'].split('/')[2] == 'travel':
            img_path = os.path.join('train/train/travel', row['img_id'])
        elif row['image_path'].split('/')[2] == 'food':
            img_path = os.path.join('train/train/food', row['img_id'])
    #elif row['from'] == 'coco':
        #img_path = os.path.join('/kaggle/input/coco-2017-dataset/coco2017/train2017', row['img_id'])

    return img_path


# Function to load images in batches and merge them into the same dataframe with a progress bar for the entire dataset
def load_images_with_progress(df, batch_size=100):
    all_batches = []  # List to store all processed batches
    
    # Create a progress bar for the entire dataset
    with tqdm(total=len(df), desc="Loading Images", unit="image") as pbar:
        for start in range(0, len(df), batch_size):
            batch = df.iloc[start:start + batch_size].copy()  # Create a copy of the batch to avoid SettingWithCopyWarning
            batch.loc[:, "new_image_path"] = batch.apply(load_image, axis=1)  # Load images for the batch
            all_batches.append(batch)  # Append the batch to the list
            
            # Update the progress bar after each batch
            pbar.update(batch_size)
    
    # Concatenate all batches back into a single dataframe
    df = pd.concat(all_batches, ignore_index=True)
    return df

In [11]:
train_real = load_images_with_progress(caption_train_sub, batch_size = 100)

Loading Images: 85300image [00:00, 101615.64image/s]

In [12]:
train_real.to_csv("train_real_with_path.csv")

In [13]:
train_real.head()

,image_path,caption_text,from,img_id,new_image_path
0,ipu24/train/travel/00000.jpg,รูปปั้นพญานาคตัวสีทองมีดอกบัวอยู่ด้านข้างอยู่ใ...,ipu24,00000.jpg,train/train/travel/00000.jpg
1,ipu24/train/travel/00000.jpg,รูปปั้นมังกรที่อยู่ภายในศาลเจ้าจีนและมีผ้าติดต...,ipu24,00000.jpg,train/train/travel/00000.jpg
2,ipu24/train/travel/00000.jpg,รูปปั้นมังกร มีหนวดสีทอง เขี้ยวและฟันสีขาว ลำต...,ipu24,00000.jpg,train/train/travel/00000.jpg
3,ipu24/train/travel/00001.jpg,โบราณสถานที่มีเจดีย์สีน้ำตาลดำมีต้นไม้หลายต้นด...,ipu24,00001.jpg,train/train/travel/00001.jpg
4,ipu24/train/travel/00001.jpg,สร้างโบราณสถานขนาดใหญ่ที่อยู่ตรงพื้นที่เต็มไปด...,ipu24,00001.jpg,train/train/travel/00001.jpg

In [14]:
train_real_fr = train_real.drop(['image_path', 'from', 'img_id',], axis=1)
train_real_fr

,caption_text,new_image_path
0,รูปปั้นพญานาคตัวสีทองมีดอกบัวอยู่ด้านข้างอยู่ใ...,train/train/travel/00000.jpg
1,รูปปั้นมังกรที่อยู่ภายในศาลเจ้าจีนและมีผ้าติดต...,train/train/travel/00000.jpg
2,รูปปั้นมังกร มีหนวดสีทอง เขี้ยวและฟันสีขาว ลำต...,train/train/travel/00000.jpg
3,โบราณสถานที่มีเจดีย์สีน้ำตาลดำมีต้นไม้หลายต้นด...,train/train/travel/00001.jpg
4,สร้างโบราณสถานขนาดใหญ่ที่อยู่ตรงพื้นที่เต็มไปด...,train/train/travel/00001.jpg
...,...,...
85236,ขนมสับปะรดที่ใส่หมูสับใส่ในจานสีขาวและมีผักสวน...,train/train/food/28002.jpg
85237,ในจานสีขาวมีสับปะรดหั่นเป็นชิ้นสามเหลี่ยมเล็ก ...,train/train/food/28002.jpg
85238,ปลาดุกย่างเสียบไม้หลายตัวตั้งอยู่ในถาดมีผักแช่...,train/train/food/28003.jpg
85239,ปลาดุกปิ้งจำนวนมากที่วางอยู่ในถาดอะลูมิเนียมทร...,train/train/food/28003.jpg
85240,ปลาดุกย่างหลายตัวเสียบไม้วางอยู่บนตะแกรงที่มีถ...,train/train/food/28003.jpg

# Train the model

In [15]:
instruction = "คิดแคปชั่นรูปนี้ให้หน่อย"
def convert_to_conversation(sample):
    conversation = [
        { "role": "user",
          "content" : [
            {"type" : "text",  "text"  : instruction},
            {"type" : "image", "image" : Image.open(sample["new_image_path"])} ]
        },
        { "role" : "assistant",
          "content" : [
            {"type" : "text",  "text"  : sample["caption_text"]} ]
        },
    ]
    return { "messages" : conversation }

In [16]:
converted_dataset = []
for index, row in tqdm(train_real_fr.iterrows()):
    converted_dataset.append(convert_to_conversation(row))
#converted_dataset = [convert_to_conversation(sample) for sample in train_real]

85241it [00:10, 7891.52it/s]

# real training

In [17]:
%%bash
pip install unsloth
# Also get the latest nightly if needed:
pip uninstall unsloth -y && pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git

Collecting unsloth
  Using cached unsloth-2026.4.2-py3-none-any.whl.metadata (55 kB)
Collecting unsloth_zoo>=2026.4.2 (from unsloth)
  Using cached unsloth_zoo-2026.4.2-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/lib/python3/dist-packages (from unsloth) (0.42.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (26.0)
Collecting torch<2.11.0,>=2.4.0 (from unsloth)
  Using cached torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Collecting torchvision (from unsloth)
  Using cached torchvision-0.26.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.4.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (7.2.2)
Collecting tyro (from unsloth)
  Using cached tyro-1.0.12-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (7.34.1)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Using cached xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth)
  Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting triton>=3.0.0 (from unsloth)
  Using cached triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting sentencepiece>=0.2.0 (from unsloth)
  Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth)
  Using cached datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Collecting accelerate>=0.34.1 (from unsloth)
  Using cached accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting peft!=0.11.0,>=0.18.0 (from unsloth)
  Using cached peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Collecting huggingface_hub>=0.34.0 (from unsloth)
  Using cached huggingface_hub-1.9.0-py3-none-any.whl.metadata (14 kB)
Collecting hf_transfer (from unsloth)
  Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting diffusers (from unsloth)
  Using cached diffusers-0.37.1-py3-none-any.whl.metadata (20 kB)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth)
  Using cached transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth)
  Using cached trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Collecting typer (from unsloth)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting pydantic (from unsloth)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.6.0)
Collecting safetensors>=0.4.3 (from accelerate>=0.34.1->unsloth)
  Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting filelock (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Collecting dill<0.4.1,>=0.3.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.33.0)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Collecting xxhash (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached xxhash-3.6.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.9.0,>=2023.1.0 (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface_hub>=0.34.0->unsloth)
  Using cached hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<2.11.0,>=2.4.0->unsloth) (82.0.1)
Collecting sympy>=1.13.3 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<2.11.0,>=2.4.0->unsloth) (3.1.6)
Collecting cuda-bindings==12.9.4 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch<2.11.0,>=2.4.0->unsloth)
  Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings==12.9.4->torch<2.11.0,>=2.4.0->unsloth)
  Using cached cuda_pathfinder-1.5.1-py3-none-any.whl.metadata (1.9 kB)
Collecting regex>=2025.10.22 (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth)
  Using cached regex-2026.4.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.4.2->unsloth)
  Using cached torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.4.2->unsloth)
  Using cached cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.4.2->unsloth) (12.1.1)
Collecting msgspec (from unsloth_zoo>=2026.4.2->unsloth)
  Using cached msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting importlib-metadata (from diffusers->unsloth)
  Using cached importlib_metadata-9.0.0-py3-none-any.whl.metadata (4.5 kB)
Collecting annotated-types>=0.6.0 (from pydantic->unsloth)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic->unsloth)
  Using cached pydantic_core-2.41.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic->unsloth)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision (from unsloth)
  Using cached torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (8.3.1)
Collecting shellingham>=1.3.0 (from typer->unsloth)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->unsloth)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->unsloth)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting docstring-parser>=0.15 (from tyro->unsloth)
  Using cached docstring_parser-0.17.0-py3-none-any.whl.metadata (3.5 kB)
Collecting typeguard>=4.0.0 (from tyro->unsloth)
  Using cached typeguard-4.5.1-py3-none-any.whl.metadata (3.8 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached aiohttp-3.13.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.3)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->unsloth)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth) (2.19.2)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch<2.11.0,>=2.4.0->unsloth)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting zipp>=3.20 (from importlib-metadata->diffusers->unsloth)
  Using cached zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<2.11.0,>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached propcache-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Using cached yarl-1.23.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->unsloth)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Using cached unsloth-2026.4.2-py3-none-any.whl (63.0 MB)
Using cached accelerate-1.13.0-py3-none-any.whl (383 kB)
Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
Using cached datasets-4.3.0-py3-none-any.whl (506 kB)
Using cached huggingface_hub-1.9.0-py3-none-any.whl (637 kB)
Using cached peft-0.18.1-py3-none-any.whl (556 kB)
Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
Using cached torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl (915.6 MB)
Using cached triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
Using cached cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 81.7 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (139.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.1/139.1 MB 54.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 23.1 MB/s eta 0:00:00
Using cached transformers-5.5.0-py3-none-any.whl (10.2 MB)
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 51.0 MB/s eta 0:00:00
Downloading unsloth_zoo-2026.4.2-py3-none-any.whl (415 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 415.2/415.2 kB 68.4 MB/s eta 0:00:00
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 91.2 MB/s eta 0:00:00:00:01
Downloading diffusers-0.37.1-py3-none-any.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 89.8 MB/s eta 0:00:00ta 0:00:01
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 89.2 MB/s eta 0:00:00:00:01
Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 463.6/463.6 kB 69.6 MB/s eta 0:00:00
Downloading pydantic_core-2.41.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 83.0 MB/s eta 0:00:00
Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 87.5 MB/s eta 0:00:00a 0:00:01m
Downloading typer-0.24.1-py3-none-any.whl (56 kB)

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Found existing installation: unsloth 2026.4.2
Uninstalling unsloth-2026.4.2:
  Successfully uninstalled unsloth-2026.4.2

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Collecting git+https://github.com/unslothai/unsloth.git
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-req-build-qe570dy5

  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-req-build-qe570dy5

  Resolved https://github.com/unslothai/unsloth.git to commit 610086744766a052cb799b17538b1238c7931659
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: unsloth
  Building wheel for unsloth (pyproject.toml): started
  Building wheel for unsloth (pyproject.toml): finished with status 'done'
  Created wheel for unsloth: filename=unsloth-2026.4.2-py3-none-any.whl size=29540575 sha256=e37055a3ae8fc3932c56936f0d3891928b0c9185a08abce482678fc7ef30be8c
  Stored in directory: /tmp/pip-ephem-wheel-cache-3hzq_vx0/wheels/60/3e/1f/e576c07051d90cf64b6a41434d87ccf4db33fafd5343bf5de0
Successfully built unsloth
Installing collected packages: unsloth
Successfully installed unsloth-2026.4.2

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [18]:
from unsloth import FastVisionModel # FastLanguageModel for LLMs
import torch

model, tokenizer = FastVisionModel.from_pretrained(
    "unsloth/Qwen3.5-4B",
    load_in_4bit = False, # Use 4bit to reduce memory use. False for 16bit LoRA.
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for long context
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
Unsloth: Your Flash Attention 2 installation seems to be broken. Using Xformers instead. No performance changes will be seen.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.4.1: Fast Qwen3_5 patching. Transformers: 5.5.0.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Unsloth: QLoRA and full finetuning all not selected. Switching to 16bit LoRA.

Loading weights:   0%|          | 0/723 [00:00<?, ?it/s]

In [19]:
model = FastVisionModel.get_peft_model(
    model,
    finetune_vision_layers     = True, # False if not finetuning vision layers
    finetune_language_layers   = True, # False if not finetuning language layers
    finetune_attention_modules = True, # False if not finetuning attention layers
    finetune_mlp_modules       = True, # False if not finetuning MLP layers

    r = 16,           # The larger, the higher the accuracy, but might overfit
    lora_alpha = 16,  # Recommended alpha == r at least
    lora_dropout = 0,
    bias = "none",
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
    # target_modules = "all-linear", # Optional now! Can specify a list if needed
)

Unsloth: Making `model.base_model.model.model.visual` require gradients

In [20]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3_5ForConditionalGeneration(
      (model): Qwen3_5Model(
        (visual): Qwen3_5VisionModel(
          (patch_embed): Qwen3_5VisionPatchEmbed(
            (proj): Conv3d(3, 1024, kernel_size=(2, 16, 16), stride=(2, 16, 16))
          )
          (pos_embed): Embedding(2304, 1024)
          (rotary_pos_emb): Qwen3_5VisionRotaryEmbedding()
          (blocks): ModuleList(
            (0-23): 24 x Qwen3_5VisionBlock(
              (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
              (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
              (attn): Qwen3_5VisionAttention(
                (qkv): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=3072, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=3072, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (proj): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (mlp): Qwen3_5VisionMLP(
                (linear_fc1): lora.Linear(
                  (base_layer): Linear(in_features=1024, out_features=4096, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=1024, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=4096, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (linear_fc2): lora.Linear(
                  (base_layer): Linear(in_features=4096, out_features=1024, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=4096, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): GELUTanh()
              )
            )
          )
          (merger): Qwen3_5VisionPatchMerger(
            (norm): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
            (linear_fc1): Linear(in_features=4096, out_features=4096, bias=True)
            (act_fn): GELU(approximate='none')
            (linear_fc2): Linear(in_features=4096, out_features=2560, bias=True)
          )
        )
        (language_model): Qwen3_5TextModel(
          (embed_tokens): Embedding(248320, 2560)
          (layers): ModuleList(
            (0-2): 3 x Qwen3_5DecoderLayer(
              (linear_attn): Qwen3_5GatedDeltaNet(
                (act): SiLUActivation()
                (conv1d): Conv1d(8192, 8192, kernel_size=(4,), stride=(1,), padding=(3,), groups=8192, bias=False)
                (norm): Qwen3_5RMSNormGated()
                (out_proj): lora.Linear(
                  (base_layer): Linear(in_features=4096, out_features=2560, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=4096, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=2560, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_qkv): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=8192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=8192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_z): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=4096, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=4096, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_b): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=32, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=32, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_a): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=32, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=32, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (mlp): Qwen3_5MLP(
                (gate_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=9216, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (up_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=9216, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (down_proj): lora.Linear(
                  (base_layer): Linear(in_features=9216, out_features=2560, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=9216, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=2560, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): SiLUActivation()
              )
              (input_layernorm): Qwen3_5RMSNorm((2560,), eps=1e-06)
              (post_attention_layernorm): Qwen3_5RMSNorm((2560,), eps=1e-06)
            )
            (3): Qwen3_5DecoderLayer(
              (self_attn): Qwen3_5Attention(
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=8192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=8192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=1024, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=1024, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (o_proj): lora.Linear(
                  (base_layer): Linear(in_features=4096, out_features=2560, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=4096, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=2560, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_norm): Qwen3_5RMSNorm((256,), eps=1e-06)
                (k_norm): Qwen3_5RMSNorm((256,), eps=1e-06)
              )
              (mlp): Qwen3_5MLP(
                (gate_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=9216, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (up_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=9216, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (down_proj): lora.Linear(
                  (base_layer): Linear(in_features=9216, out_features=2560, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=9216, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=2560, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): SiLUActivation()
              )
              (input_layernorm): Qwen3_5RMSNorm((2560,), eps=1e-06)
              (post_attention_layernorm): Qwen3_5RMSNorm((2560,), eps=1e-06)
            )
            (4-6): 3 x Qwen3_5DecoderLayer(
              (linear_attn): Qwen3_5GatedDeltaNet(
                (act): SiLUActivation()
                (conv1d): Conv1d(8192, 8192, kernel_size=(4,), stride=(1,), padding=(3,), groups=8192, bias=False)
                (norm): Qwen3_5RMSNormGated()
                (out_proj): lora.Linear(
                  (base_layer): Linear(in_features=4096, out_features=2560, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=4096, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=2560, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_qkv): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=8192, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=8192, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_z): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=4096, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=4096, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_b): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=32, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=32, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (in_proj_a): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=32, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=2560, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=32, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (mlp): Qwen3_5MLP(
                (gate_proj): lora.Linear(
                  (base_layer): Linear(in_features=2560, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(

In [21]:
from unsloth import is_bf16_supported
from unsloth.trainer import UnslothVisionDataCollator
from trl import SFTTrainer, SFTConfig

FastVisionModel.for_training(model) # Enable for training!

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    data_collator = UnslothVisionDataCollator(model, tokenizer), # Must use!
    train_dataset = converted_dataset,
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 150,
        # num_train_epochs = 1, # Set this instead of max_steps for full training runs
        learning_rate = 2e-4,
        fp16 = not is_bf16_supported(),
        bf16 = is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none",     # For Weights and Biases

        # You MUST put the below items for vision finetuning:
        remove_unused_columns = False,
        dataset_text_field = "",
        dataset_kwargs = {"skip_prepare_dataset": True},
        dataset_num_proc = 4,
        max_seq_length = 2048,
    ),
)

Unsloth: Model does not have a default image size - using 512

[accelerate.utils.other|WARNING][RANK 0] Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

In [22]:
trainer_stats = trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 248046}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 85,241 | Num Epochs = 1 | Total steps = 150
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 38,756,352 of 4,578,021,888 (0.85% trained)

Unsloth: Will smartly offload gradients to save VRAM!

# Process the test set

In [49]:
FastVisionModel.for_inference(model) # Enable for inference!

instruction = "คิดแคปชั่นรูปนี้ให้หน่อย"
test_cap = []
def generateCaption(image_path):
    image = Image.open(image_path)
    messages = [
        {"role": "user", "content": [
            {"type": "image"},
            {"type": "text", "text": instruction}
        ]}
    ]
    input_text = tokenizer.apply_chat_template(messages, add_generation_prompt = True)
    inputs = tokenizer(
        image,
        input_text,
        add_special_tokens = False,
        return_tensors = "pt",
    ).to("cuda")
    
    output = model.generate(**inputs, max_new_tokens = 100,
                       use_cache = True, temperature = 0.7, min_p = 0.1)
    caption = tokenizer.decode(output[0], skip_special_tokens=True)
    test_cap.append(caption)

In [50]:
folder_path = 'test/test'

image_paths = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
            image_paths.append(os.path.join(root, file))

print(len(image_paths))

2000

In [ ]:
for img_path in tqdm(image_paths):
    generateCaption(img_path)

  1%|▏         | 25/2000 [01:05<1:12:51,  2.21s/it]

In [ ]:
test_cap[0]

In [ ]:
image_id = [k.split('/')[-1] for k in image_paths]

In [ ]:
image_id_real = [k.split('.')[0] for k in image_id]

In [ ]:
data = {'image_id': image_id_real, 'cc': test_cap}

# Create a DataFrame
submission = pd.DataFrame(data)

In [ ]:
submission.to_csv("test_ans_1.csv")

In [ ]:
submission['cc'] = submission['cc'].apply(lambda x: x.split('\n')[-1])

In [ ]:
submission['cc'] = submission['cc'].apply(lambda x: x.replace('"',''))

In [ ]:
submission

In [ ]:
submission.to_csv("first_sub1.csv")

# align labels

In [ ]:
sample = pd.read_csv('sample_submission.csv', dtype={'image_id': str})

In [ ]:
sampleid = sample['image_id']

In [ ]:
id_list = sampleid.to_list()

In [ ]:
id_list[:5]

In [ ]:
submission.head()

In [ ]:
df_final = submission.set_index('image_id').loc[id_list].reset_index()

In [ ]:
df_final = df_final.rename(columns={'cc': 'caption'})

In [ ]:
df_final['caption'][0]

In [44]:
df_final

     image_id                                            caption
0       01354    ราสีขาวที่ขึ้นอยู่บริเวณบนใบไม้สีน้ำตาลขนาดใหญ่
1       01413   งูเห่าตัวหนึ่งที่มีสีน้ำตาลและสีเทาอยู่บนพื้นไม้
2       01802  บ้านไม้หลายหลังที่ตั้งอยู่บนหน้าผาหินขนาดใหญ่แ...
3       01243  ลิงตัวหนึ่งนั่งอยู่ใกล้กับกำแพงสีขาวและมีหญ้าอ...
4       00693  แมลงที่มีปีกสีน้ำตาลมีจุดสีขาวและจุดสีส้มอยู่บ...
...       ...                                                ...
1995    00029  ภายในอาคารมีต้นไม้หลายต้น มีบ่อน้ำ มีป้าย มีคน...
1996    01065  ดอกสีแดงหลายดอกติดอยู่บนกิ่งไม้และมีใบสีเขียวอ...
1997    00195  ต้นไม้ขนาดใหญ่ที่มีใบสีเขียวตั้งอยู่บริเวณริมถ...
1998    01026     ดอกสีเหลืองและสีน้ำตาลติดอยู่บนต้นไม้อยู่ในป่า
1999    01345  ป้ายสีชมพูขนาดใหญ่ที่ตั้งอยู่หน้าวัดและมีต้นไม...

[2000 rows x 2 columns]

In [ ]:
df_final.to_csv('QWEN3.5_caption_temp0.7.csv', index=False)